// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOyHZ6AY7OPimqlFEl1H9ZuAwL82ACnIU',
    appId: '1:606922092381:web:3cbcd677f5d53f0a1a02b4',
    messagingSenderId: '606922092381',
    projectId: 'chat-box-9a9d1',
    authDomain: 'chat-box-9a9d1.firebaseapp.com',
    storageBucket: 'chat-box-9a9d1.appspot.com',
    measurementId: 'G-XWK2QEPVQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9KojqsIV2nLdgA4eyCbfaw70r0AX3XY',
    appId: '1:606922092381:android:a205dec09fb8dd761a02b4',
    messagingSenderId: '606922092381',
    projectId: 'chat-box-9a9d1',
    storageBucket: 'chat-box-9a9d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqZ_EjG_oWcliomcRj1tZ77m9yWbT0d0M',
    appId: '1:606922092381:ios:8b18d3458855249b1a02b4',
    messagingSenderId: '606922092381',
    projectId: 'chat-box-9a9d1',
    storageBucket: 'chat-box-9a9d1.appspot.com',
    iosClientId: '606922092381-npkldiaddpirmu7mengp7d1hsf4344ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqZ_EjG_oWcliomcRj1tZ77m9yWbT0d0M',
    appId: '1:606922092381:ios:8b18d3458855249b1a02b4',
    messagingSenderId: '606922092381',
    projectId: 'chat-box-9a9d1',
    storageBucket: 'chat-box-9a9d1.appspot.com',
    iosClientId: '606922092381-npkldiaddpirmu7mengp7d1hsf4344ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOyHZ6AY7OPimqlFEl1H9ZuAwL82ACnIU',
    appId: '1:606922092381:web:4ed60462f25893b41a02b4',
    messagingSenderId: '606922092381',
    projectId: 'chat-box-9a9d1',
    authDomain: 'chat-box-9a9d1.firebaseapp.com',
    storageBucket: 'chat-box-9a9d1.appspot.com',
    measurementId: 'G-68S20P2P4W',
  );

}